version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: aihelper-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: aihelper
      POSTGRES_USER: app
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: aihelper-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
    ports:
      - "5051:80"
    depends_on:
      - postgres

  redis:
    image: redis:7-alpine
    container_name: aihelper-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pg_data: